feat: update sudo to 1.9.15p5-3

diff --git a/scripts/mkpkg b/scripts/mkpkg
--- a/scripts/mkpkg
+++ b/scripts/mkpkg
@@ -2,7 +2,7 @@
 #
 # SPDX-License-Identifier: ISC
 #
-# Copyright (c) 2010-2020 Todd C. Miller <Todd.Miller@sudo.ws>
+# Copyright (c) 2010-2023 Todd C. Miller <Todd.Miller@sudo.ws>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -17,7 +17,8 @@
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
 # Build a binary package using polypkg
-# Usage: mkpkg [--debug] [--flavor flavor] [--platform platform] [--osversion ver]
+# Usage: mkpkg [--build-only] [--configure-only] [--debug] [--flavor flavor]
+#              [--platform platform] [--osversion ver]
 #
 
 # Make sure IFS is set to space, tab, newline in that order.
@@ -28,10 +29,12 @@ nl='
 IFS=" 	$nl"
 
 # Parse arguments
-usage="usage: mkpkg [--debug] [--flavor flavor] [--platform platform] [--osversion ver]"
+usage="usage: mkpkg [--build-only] [--configure-only] [--debug] [--flavor flavor] [--platform platform] [--osversion ver]"
 debug=0
 flavor=vanilla
 crossbuild=false
+build_packages=true;
+build_sudo=true;
 while test $# -gt 0; do
     case "$1" in
 	--debug)
@@ -80,6 +83,12 @@ while test $# -gt 0; do
 	    crossbuild=true
 	    configure_opts="${configure_opts}${configure_opts+$tab}$1"
 	    ;;
+	--build-only)
+	    build_packages=false
+	    ;;
+	--configure-only)
+	    build_sudo=false
+	    ;;
 	*)
 	    # Pass unknown options to configure
 	    configure_opts="${configure_opts}${configure_opts+$tab}$1"
@@ -91,10 +100,14 @@ done
 scriptdir=`dirname $0`
 configure="${scriptdir}/../configure"
 
-: ${osversion="`$scriptdir/pp --probe`"}
-test -n "$osversion" || exit 1
+: ${osversion="`$scriptdir/pp --probe 2>/dev/null || echo unknown`"}
 osrelease=`echo "$osversion" | sed -e 's/^[^0-9]*//' -e 's/-.*$//'`
 : ${MAKE=make}
+
+if [ $build_packages = true -a "$osversion" = "unknown" ]; then
+    echo "unable to determine platform" 1>&2
+    exit 1
+fi
 
 # If using GNU make, set number of jobs
 if ${MAKE} --version 2>&1 | grep GNU >/dev/null; then
@@ -105,10 +118,10 @@ if ${MAKE} --version 2>&1 | grep GNU >/dev/null; then
 	    NJOBS=`sysctl -n hw.ncpu`
 	    ;;
 	Linux)
-	    if [ -r /proc/cpuinfo ]; then
-		for c in `sed -n 's/^cpu cores[	 ]*: *//p' /proc/cpuinfo`; do
-		    NJOBS=`expr $NJOBS + $c`
-		done
+	    if [ -x /usr/bin/nproc ]; then
+		NJOBS=`/usr/bin/nproc`
+	    elif [ -r /proc/cpuinfo ]; then
+		NJOBS=`grep ^processor /proc/cpuinfo | wc -l`
 	    fi
 	    ;;
 	SunOS)
@@ -136,9 +149,9 @@ fi
 if [ "$crossbuild" = "false" ]; then
     case "$osversion" in
 	FreeBSD*|macos*)
-	    # Use the system compiler on FreeBSD and macOS
-	    if [ -z "$CC" -a -x /usr/bin/cc ]; then
-		CC=/usr/bin/cc; export CC
+	    # Use clang, not gcc, on FreeBSD and macOS
+	    if [ -z "$CC" ]; then
+		CC=clang; export CC
 	    fi
 	    ;;
     esac
@@ -160,7 +173,7 @@ case "$osversion" in
     centos*|rhel*|f[0-9]*)
 	case "$osversion" in
 	    centos*|rhel*)
-		osmajor=`sed -n -e 's/^.*release \([0-9]*\)[^0-9].*$/\1/p' /etc/redhat-release`
+		osmajor=`sed -n -e 's/^.*release \([0-9][0-9]*\).*$/\1/p' /etc/redhat-release`
 		if [ $osmajor -ge 4 ]; then
 		    # RHEL 4 and up support SELinux
 		    with_selinux=true
@@ -269,6 +282,35 @@ case "$osversion" in
 	make_opts="${make_opts}${make_opts+ }"'docdir=$(datarootdir)/doc/packages/$(PACKAGE_TARNAME)'
 	;;
     deb*|ubu*)
+	# Sudo-specific executables moved to /usr/libexec/sudo starting in
+	# Debian: Debian 12 (Bookworm)
+	# Ubuntu: Ubuntu 22.04 (Jammy Jellyfish)
+	# Previously, they were stored in /usr/lib/sudo.
+	libexec=lib
+
+	# AppArmor is enabled by default starting in
+	# Debian: Debian 10 (Buster)
+	# Ubuntu: Ubuntu 12.04 (Precise Pangolin)
+	osmajor=`sed -n -e 's/^VERSION_ID=\"\([0-9]*\).*$/\1/p' /etc/os-release`
+	case "$osversion" in
+	    deb*)
+		if [ -z $osmajor ] || [ $osmajor -ge 10 ]; then
+		    with_apparmor=true
+		fi
+		if [ -z $osmajor ] || [ $osmajor -ge 12 ]; then
+		    libexec=libexec
+		fi
+		;;
+	    ubu*)
+		if [ -z $osmajor ] || [ $osmajor -ge 14 ]; then
+		    with_apparmor=true
+		fi
+		if [ -z $osmajor ] || [ $osmajor -ge 22 ]; then
+		    libexec=libexec
+		fi
+		;;
+	esac
+
 	# Encrypted remote I/O log support.
 	with_openssl=true
 	# Python plugins
@@ -295,6 +337,9 @@ case "$osversion" in
 		configure_opts="${configure_opts}${configure_opts+$tab}--with-sssd-lib=/usr/lib/$MULTIARCH"
 	    fi
 	fi
+	if [ X"$with_apparmor" = X"true" ]; then
+		configure_opts="${configure_opts}${configure_opts+$tab}--with-apparmor"
+	fi
 	configure_opts="--prefix=/usr
 		--with-all-insults
 		--with-pam
@@ -310,15 +355,14 @@ case "$osversion" in
 		--disable-root-mailer
 		--with-sendmail=/usr/sbin/sendmail
 		--mandir=/usr/share/man
-		--libexecdir=/usr/lib
-		--with-selinux
+		--libexecdir=/usr/$libexec
 		--with-linux-audit
 		$configure_opts"
 	# Use correct libaudit dependency
 	for f in /lib/${MULTIARCH}${MULTIARCH:+/}libaudit.so.[0-9]* /lib/libaudit.so.[0-9]*; do
 	    if [ -f "$f" ]; then
 		linux_audit=`dpkg-query -S "$f" 2>/dev/null | sed -n 's/:.*//p'`
-		test -n "$linux_audit" && break;
+		test -n "$linux_audit" && break
 	    fi
 	done
 	if [ -z "$linux_audit" ]; then
@@ -327,7 +371,7 @@ case "$osversion" in
 	fi
 	PPVARS="${PPVARS}${PPVARS+$space}linux_audit=$linux_audit"
 	# Use correct libssl dependency
-	libssl_dep=`dpkg-query -S /usr/lib/${MULTIARCH}${MULTIARCH:+/}libssl.so.1.[0-9]* /lib/${MULTIARCH}${MULTIARCH:+/}libssl.so.1.[0-9]* 2>/dev/null | sort -rn | awk -F: '{ print $1; exit }'`
+	libssl_dep=`dpkg-query -S /usr/lib/${MULTIARCH}${MULTIARCH:+/}libssl.so.[1-9]* /lib/${MULTIARCH}${MULTIARCH:+/}libssl.so.[1-9]* 2>/dev/null | sort -rn | awk -F: '{ print $1; exit }'`
 	if [ -z "$libssl_dep" ]; then
 	    echo "unable to determine package for libssl" 1>&2
 	    exit 1
@@ -350,20 +394,34 @@ case "$osversion" in
 	    sdkvers=`echo "${osversion}" | sed -e 's/^macos\([0-9][0-9]\)\([0-9]*\)-.*$/\1.\2/' -e 's/\.$//'`
 	    # SDKs may be under Xcode.app or CommandLineTools (for non-Xcode)
 	    if [ -d "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs" ]; then
-		SDK_DIR="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
+		SDKS="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
 	    elif [ -d "/Library/Developer/CommandLineTools/SDKs" ]; then
-		SDK_DIR="/Library/Developer/CommandLineTools/SDKs"
+		SDKS="/Library/Developer/CommandLineTools/SDKs"
 	    else
 		echo "unable to find macOS SDKs directory" 1>&2
 		exit 1
 	    fi
-	    SDK_DIR="${SDK_DIR}/MacOSX${sdkvers}.sdk"
-	    if [ -d "${SDK_DIR}" ]; then
-		SDK_FLAGS="-isysroot ${SDK_DIR} -mmacosx-version-min=${sdkvers}"
-	    else
-		echo "unable to find SDKs directory for macOS $sdkvers" 1>&2
-		exit 1
-	    fi
+	    while :; do
+		SDK_DIR="${SDKS}/MacOSX${sdkvers}.sdk"
+		if [ -d "${SDK_DIR}" ]; then
+		    SDK_FLAGS="-isysroot ${SDK_DIR} -mmacosx-version-min=${sdkvers}"
+		    break
+		fi
+		case "$sdkvers" in
+		*.00)
+		    # Try MacOSXMM.0.sdk
+		    sdkvers=${sdkvers%0}
+		    ;;
+		*.0)
+		    # Try MacOSXMM.sdk
+		    sdkvers=${sdkvers%.0}
+		    ;;
+		*)
+		    echo "missing $SDK_DIR" 1>&2
+		    exit 1
+		    ;;
+		esac
+	    done
 	fi
 	export CFLAGS="-O2 -g $ARCH_FLAGS $SDK_FLAGS"
 	export LDFLAGS="$ARCH_FLAGS $SDK_FLAGS"
@@ -383,7 +441,7 @@ case "$osversion" in
     aix*)
 	# TODO: openssl (AIX freeware?)
 	# Use -gxcoff with gcc instead of -g for dbx-style debugging symbols.
-	if [ -z "$CC" && gcc -v >/dev/null 2>&1 ]; then
+	if test -z "$CC" && gcc -v >/dev/null 2>&1; then
 	    CFLAGS="-O2 -gxcoff"; export CFLAGS
 	fi
 	# Note, must indent with tabs, not spaces due to IFS trickery
@@ -403,7 +461,7 @@ case "$osversion" in
 		$configure_opts"
 	PPVARS="${PPVARS}${PPVARS+$space}aix_freeware=true"
 	;;
-    FreeBSD*)
+    FreeBSD*|DragonFly*)
 	# Encrypted remote I/O log support.
 	with_openssl=true
 
@@ -431,8 +489,15 @@ case "$osversion" in
 
 		if [ $osrelease -ge 11 ]; then
 		    # Build 64-bit binaries on Solaris 11 and above.
-		    CFLAGS="${CFLAGS:--O2 -g} -m64"; export CFLAGS
-		    LDFLAGS="-m64${LDFLAGS:+ }${LDFLAGS}"; export LDFLAGS
+		    case "${CC}${CFLAGS}" in
+		      *-m32*|*-m64*)
+			# User specified memory model flags
+			;;
+		      *) 
+			CFLAGS="${CFLAGS:--O2 -g} -m64"; export CFLAGS
+			LDFLAGS="-m64${LDFLAGS:+ }${LDFLAGS}"; export LDFLAGS
+			;;
+		    esac
 		    # Solaris audit is not supported by Illumos
 		    if [ X"`uname -o 2>/dev/null`" = X"illumos" ]; then
 			configure_opts="${configure_opts}${configure_opts+$tab}--with-bsm-audit"
@@ -451,7 +516,7 @@ case "$osversion" in
 			    PYTHON="/usr/bin/python3"; export PYTHON
 			else
 			    # Sometimes the /usr/bin/python3 is missing
-			    for f in /usr/bin/python3.9 /usr/bin/python3.8 /usr/bin/python3.7 /usr/bin/python3.6 /usr/bin/python3.5 /usr/bin/python3.4 /usr/bin/python3.3 /usr/bin/python3.2 /usr/bin/python3.1 /usr/bin/python3.0; do
+			    for f in /usr/bin/python3.11 /usr/bin/python3.10 /usr/bin/python3.9 /usr/bin/python3.8 /usr/bin/python3.7 /usr/bin/python3.6 /usr/bin/python3.5 /usr/bin/python3.4; do
 				if [ -x $f ]; then
 				    PYTHON="$f"; export PYTHON
 				    break
@@ -488,9 +553,12 @@ case "$osversion" in
 	;;
 esac
 
-# Don't enable OpenSSL if user disabled it.
+# Don't enable OpenSSL or python if disabled by the user.
 case "$configure_opts" in
     *--disable-openssl*) with_openssl=false;;
+esac
+case "$configure_opts" in
+    *--disable-python*) with_python=false;;
 esac
 if [ X"$with_openssl" = X"true" ]; then
     configure_opts="${configure_opts}${configure_opts+$tab}--enable-openssl"
@@ -511,8 +579,12 @@ if [ -r Makefile ]; then
     ${MAKE} $make_opts distclean
 fi
 ${configure} "$@" || exit $?
-${MAKE} $make_opts || exit $?
-${MAKE} $make_opts PPFLAGS="$PPFLAGS" PPVARS="$PPVARS" package
+if [ $build_sudo = true ]; then
+    ${MAKE} $make_opts || exit $?
+    if [ $build_packages = true ]; then
+	${MAKE} $make_opts PPFLAGS="$PPFLAGS" PPVARS="$PPVARS" package
+    fi
+fi
 exitval=$?
 test $debug -eq 0 && rm -rf destdir
 
